CREATE TABLE IF NOT EXISTS flags (
    name VARCHAR(50) PRIMARY KEY,
    code INTEGER NOT NULL,
    msg TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

